#ifndef JPSUMO_HWREV_H
#define JPSUMO_HWREV_H

typedef enum _jpsumo_hw_version_t
{
	JPSUMO_CLASSIC_HW_A1 = 0,
	JPSUMO_CLASSIC_HW_A2,
	JPSUMO_CLASSIC_HW_A3,
	JPSUMO_CLASSIC_HW_B1,
	JPSUMO_CLASSIC_HW_B2,
	JPSUMO_CLASSIC_HW_06,
	JPSUMO_CLASSIC_HW_07,
	JPSUMO_EVO_HW_00,
	JPSUMO_EVO_HW_01,
	JPSUMO_EVO_HW_02,
	JPSUMO_V3_HW_00,
} jpsumo_hw_version_t;

#endif
