#add parrot drivers here
#obj-y += serial/
obj-y += nand/
obj-y += video/
obj-y += usb/serial/blackberry/
obj-y += i2c/
obj-y += p264/
obj-y += sound/p5p_aai/
obj-y += power/
obj-y += sound/p6_aai/
obj-y += media/video/
obj-y += spi/
obj-y += net/
obj-y += mmc/
obj-y += input/
obj-y += char/
obj-y += ultra_sound/
obj-y += misc/
obj-y += pressure/

# Without this, built-in.o won't be created when it's empty, and the
# final vmlinux link will fail.
obj-y += dummy.o
